# Imagem base oficial Python
FROM python:3.12-slim

# Diretório de trabalho
WORKDIR /app

# Copiar dependências
COPY requirements.txt .

# Instalar dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo o código do projeto
COPY . .

# Expor porta (caso use SSE/HTTP)
EXPOSE 8000

# Rodar servidor
CMD ["python", "server.py"]