# Imagem base oficial Python 3.12 slim
FROM python:3.12-slim

# Diretório de trabalho dentro do container
WORKDIR /app

# Copiar arquivos de dependências primeiro (para aproveitar cache)
COPY requirements.txt .

# Instalar dependências
RUN pip install --no-cache-dir -r requirements.txt

# Expôr a porta que a API vai rodar
EXPOSE 8000

# Comando de execução
CMD ["python", "server.py"]